# Generated by Django 4.2.6 on 2023-10-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADM', 'Administrateur'), ('COM', 'Commercial'), ('SUP', 'Support'), ('GES', 'Gestion')], max_length=55, verbose_name='Type de rôle'),
        ),
    ]
