# Generated by Django 4.2.6 on 2023-12-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateField()),
                ('amount_contract', models.FloatField(default=0)),
                ('saldo_contract', models.FloatField(default=0)),
                ('status_contract', models.CharField(choices=[('SI', 'Signed'), ('NS', 'Not signed'), ('CA', 'Cancelled')], max_length=55, verbose_name='Statut')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('begin_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('location', models.CharField(max_length=55, verbose_name='localisation')),
                ('notes', models.TextField(blank=True, max_length=2048, verbose_name='Evènement')),
                ('attendees_count', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.contract')),
                ('support_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=55, verbose_name="Nom de l'entreprise")),
                ('client_name', models.CharField(max_length=55, verbose_name='Responsable client')),
                ('information', models.TextField(blank=True, max_length=2048, verbose_name='Information')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contact Commercial')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.customer'),
        ),
    ]
